import js from "@eslint/js";
import svelte from "eslint-plugin-svelte";
import globals from "globals";
import ts from "typescript-eslint";
import svelteConfig from "./svelte.config.js";

// Type-aware rules (ts.configs.recommendedTypeChecked) are deliberately not
// enabled: `bun run typecheck` already runs tsc and svelte-check over the same
// files, so turning them on here would duplicate that gate at a large cost in
// lint time.
export default ts.config(
  {
    // Generated by shadcn-svelte, not hand-edited. tsconfig.json excludes the
    // .ts files here for the same reason.
    ignores: ["src/lib/components/ui/**", ".svelte-kit/**", "build/**", "coverage/**", "node_modules/**"],
  },
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    rules: {
      // Underscore marks a parameter that is deliberately unused, e.g. one kept
      // only to hold a signature stable for callers.
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      // resolve() exists to prefix internal routes with a configured base path.
      // Every link here is an absolute GitHub URL opened in a new tab, and this
      // app has a single route, so the rule only produces false positives.
      "svelte/no-navigation-without-resolve": "off",
    },
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts", "**/*.svelte.js"],
    languageOptions: {
      parserOptions: {
        extraFileExtensions: [".svelte"],
        parser: ts.parser,
        svelteConfig,
      },
    },
  },
);
