// LaunchAgent plist for the dashboard *window* login item, rendered in code so
// the dev checkout and the packaged install share one implementation (the
// ProgramArguments differ per mode, which a sed template handled poorly).
//
// The agent runs `attn open` (or the checkout equivalent) once at login to
// open a dedicated Chrome app window pointed at the dashboard, so the page's
// client-side Notification code stays connected in the background.
//
// Deliberately has no KeepAlive: closing the window should not force it back
// open; log back in (or re-run install-window) to reopen it.

export interface WindowAgentSpec {
  label: string;
  // Argv of the login item, absolute paths, passed through verbatim.
  programArgs: string[];
  // PATH for the launchd-spawned process; launchd inherits nothing.
  path: string;
  port: number;
  logDir: string;
}

// The label is shared by both modes (and predates them), so reinstalling from
// either a checkout or a package replaces the existing agent instead of
// leaving an orphan behind.
export function windowAgentLabel(username: string): string {
  return `com.${username}.attn-window`;
}

function xmlEscape(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

export function renderWindowPlist(spec: WindowAgentSpec): string {
  const args = spec.programArgs.map((arg) => `        <string>${xmlEscape(arg)}</string>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by attn (install-window); do not edit by hand. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${xmlEscape(spec.label)}</string>

    <key>ProgramArguments</key>
    <array>
${args}
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${xmlEscape(spec.path)}</string>
        <key>ATTN_PORT</key>
        <string>${String(spec.port)}</string>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${xmlEscape(`${spec.logDir}/window.out.log`)}</string>
    <key>StandardErrorPath</key>
    <string>${xmlEscape(`${spec.logDir}/window.err.log`)}</string>
</dict>
</plist>
`;
}
