import { fetchSteps, reviewRefs, safePrNumber, safeRef, shellQuote } from "./local-review";
import type { WatchItem } from "./types";

// Builds the zsh script that "Open review terminal" runs in a new Terminal
// window: cd into the local clone and fetch the PR into refs/attn/, without
// checking it out (see reviewRefs for why).
//
// This is the one place where the dashboard executes commands on the machine
// rather than mutating local state, so the same injection rules as
// local-review.ts apply: the base ref is PR-author-controlled and is only
// inlined when it passes safeRef(), and the PR number must be an integer.
// Free-text values (title, paths) are inlined only through shellQuote(), and
// printed with `print -r`: zsh's `echo` expands backslash escapes even inside
// single quotes, so a title like `\e[2J` could redraw the window.

export { shellQuote };

// Removes control characters (C0, DEL, C1) from GitHub text bound for a
// terminal, so a PR author cannot send escape sequences that clear the screen,
// fake output, or set the window title.
export function terminalText(value: string): string {
  // eslint-disable-next-line no-control-regex
  return value.replace(/[\u0000-\u001f\u007f-\u009f]/g, "");
}

export function terminalScriptFileName(item: WatchItem): string {
  const repo = item.repoName.replace(/[^A-Za-z0-9._-]/g, "-");
  // .command is what makes macOS `open` run the file in Terminal. Validate the
  // number so a tainted value cannot traverse out of the state dir.
  return `review-${repo}-${safePrNumber(item.number)}.command`;
}

export function buildReviewTerminalScript(item: WatchItem): string {
  if (!item.kind.startsWith("pr_")) {
    throw new Error("Review terminals are only available for PR notifications.");
  }
  if (!item.localPath) {
    throw new Error(`No local checkout of ${item.repo} was found by the dashboard.`);
  }

  const number = safePrNumber(item.number);
  const base = safeRef(item.baseBranch) || "main";
  const refs = reviewRefs(item);
  const heading = terminalText(`${item.repo} #${number}: ${item.title}`);

  return `#!/bin/zsh
# Generated by attn. Fetches a PR for review without checking it out.
print -r -- ${shellQuote(heading)}
print -r -- ${shellQuote(terminalText(item.url))}
echo

cd ${shellQuote(item.localPath)} || { echo "Checkout path is missing." >&2; exec zsh; }

${fetchSteps(item, base)} \\
  && { echo; echo ${shellQuote(`Fetched without checking anything out. Review with: git diff ${refs.base}...${refs.head}`)}; } \\
  || echo "Fetch failed; see the output above." >&2

exec zsh
`;
}
