import { checkoutSteps, safeRef } from "./local-review";
import type { WatchItem } from "./types";

// Builds the zsh script that "Open review terminal" runs in a new Terminal
// window: cd into the local checkout and check out the PR branch.
//
// This is the one place where the dashboard executes commands on the machine
// rather than mutating local state, so the same injection rules as
// local-review.ts apply: branch and base refs are PR-author-controlled and
// are only inlined when they pass safeRef(); otherwise the script fetches the
// PR head by its integer number. Free-text values (title, paths) are inlined
// only through shellQuote(). The script refuses to touch a dirty working tree
// rather than stashing the user's work.

export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

export function terminalScriptFileName(item: WatchItem): string {
  const repo = item.repoName.replace(/[^A-Za-z0-9._-]/g, "-");
  // .command is what makes macOS `open` run the file in Terminal.
  return `review-${repo}-${item.number}.command`;
}

export function buildReviewTerminalScript(item: WatchItem): string {
  if (!item.kind.startsWith("pr_")) {
    throw new Error("Review terminals are only available for PR notifications.");
  }
  if (!item.localPath) {
    throw new Error(`No local checkout of ${item.repo} was found by the dashboard.`);
  }

  const base = safeRef(item.baseBranch) || "main";
  const headBranch = safeRef(item.headBranch);
  const branch = headBranch || `pr-${item.number}`;
  const heading = `${item.repo} #${item.number}: ${item.title}`;

  return `#!/bin/zsh
# Generated by ghe-notification-watch. Checks out a PR branch for review.
echo ${shellQuote(heading)}
echo ${shellQuote(item.url)}
echo

cd ${shellQuote(item.localPath)} || { echo "Checkout path is missing." >&2; exec zsh; }

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree is dirty — commit or stash before switching branches." >&2
  echo "This launcher never stashes your work for you." >&2
  exec zsh
fi

(
  set -e
${checkoutSteps(item, base, headBranch)
  .split("\n")
  .map((line) => `  ${line}`)
  .join("\n")}
) && { echo; echo ${shellQuote(`Ready. Review with: git diff ${base}...${branch}`)}; } \\
  || echo "Checkout failed — see output above." >&2

exec zsh
`;
}
